# Generated by Django 5.1.1 on 2024-10-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_regimento_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='regimentocadastro',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10),
        ),
    ]
