# Generated by Django 5.1.1 on 2024-10-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='disciplinas_aprovadas',
            field=models.ManyToManyField(blank=True, related_name='inscricoes_aprovadas', to='website.disciplina'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='inscricoes_disciplinas', to='website.disciplina'),
        ),
    ]
