# Generated by Django 5.1.1 on 2024-10-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_inscricao_disciplinas_aprovadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='nota_prova',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
