# Generated by Django 5.1.1 on 2024-10-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_inscricao_nota_prova'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
